[package]
name = "p3-code"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../../Plonky3/field" }
p3-matrix = { path = "../../Plonky3/matrix" }

[dev-dependencies]
p3-mersenne-31 = { path = "../../Plonky3/mersenne-31" }
